# Generated by Django 2.2.5 on 2022-03-17 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(choices=[('Creator', 'Creator'), ('Listener', 'Listener'), ('Producer', 'Producer')], default='Listener', max_length=10)),
                ('image', models.ImageField(default='images/default.png', max_length=200, upload_to='images/%Y/%m', verbose_name='Profile photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('average_rating', models.IntegerField(default=0)),
                ('album_title', models.CharField(max_length=64)),
                ('link', models.URLField(unique=True)),
                ('title', models.CharField(max_length=64)),
                ('creator', models.ManyToManyField(to='soundshare.UserProfile')),
            ],
        ),
    ]
