# Generated by Django 2.2.26 on 2022-03-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Listener', 'Listener'), ('Producer', 'Producer')], default='Listener', max_length=6),
        ),
    ]
