# Generated by Django 2.2.26 on 2022-03-07 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soundshare', '0002_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='owner',
        ),
    ]
