# Generated by Django 2.2.26 on 2022-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soundshare', '0003_remove_userprofile_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('album_title', models.CharField(max_length=64)),
                ('link', models.URLField(unique=True)),
                ('title', models.CharField(max_length=64)),
                ('creator', models.ManyToManyField(to='soundshare.UserProfile')),
            ],
        ),
    ]
